### ISSUE TITLE
Integrations hassio

### ISSUE THREAD

**Issue by danyxx** [BionicWeb/AxpertPi#1]
Excellent work. Can you integrate with hassio?

**Comment by BionicWeb** [comment]
Hi, I have started to create a hassio integration if you are still interested?

**Comment by BionicWeb** [comment]
Turn on advanced mode for your user, then add the following custom repo to your addons in hassio, https://github.com/BionicWeb/hassio-repo.git. Install the addon and then check the config, it is default for Kodak King 5kw ( PIP-5048MK ). Regards
